FROM elixir:1.7 AS build

COPY apps apps
COPY Makefile Makefile
COPY mix.exs mix.exs
COPY mix.lock mix.lock
COPY config config

RUN rm -Rf _build && \
  mix local.hex --force && \
  mix local.rebar --force && \
  make
